require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'

source 'https://cdn.cocoapods.org/'
source 'https://github.com/Mapsted/podspec-simulator.git' #Simulator - Xcode 15.0


use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorGeolocation', :path => '../../node_modules/@capacitor/geolocation'
  pod 'Mapsted', :path => '../../../mapsted'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
  pod 'mapsted-sdk-map-ui', '~> 5.0'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end
